#!/bin/bash
if [ ! -d ~/badckup ]; then
    mkdir -p ~/backup
fi

if [ $# == 0 ]; then
    echo "parameters must be specified."
    exit 1
else
    if [ $# == 1 -a "$1" == "--clean" ]; then
        rm -rf ~/backup/*
        echo files in dir ~/backup are removed.
        exit 0
    fi
    mv $* ~/backup
    if [ $? == 0 ]; then
        echo $* moved to ~/backup
    else
        echo mv $* to ~/backup fail
        exit 2
    fi
fi

